// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFavouriteUser = "favourite_users"

// FavouriteUser mapped from table <favourite_users>
type FavouriteUser struct {
	ID        string    `gorm:"column:id;type:uuid;primaryKey;default:uuid_generate_v4()" json:"id"`
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	CreatedBy string    `gorm:"column:created_by;type:uuid;not null" json:"created_by"`
	ProfileID string    `gorm:"column:profile_id;type:uuid;not null" json:"profile_id"`
}

// TableName FavouriteUser's table name
func (*FavouriteUser) TableName() string {
	return TableNameFavouriteUser
}
