// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFcmToken = "fcm_tokens"

// FcmToken mapped from table <fcm_tokens>
type FcmToken struct {
	ID        string    `gorm:"column:id;type:uuid;primaryKey;default:uuid_generate_v4()" json:"id"`
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	CreatedBy string    `gorm:"column:created_by;type:uuid;not null" json:"created_by"`
	Token     string    `gorm:"column:token;type:text;not null" json:"token"`
}

// TableName FcmToken's table name
func (*FcmToken) TableName() string {
	return TableNameFcmToken
}
